os: linux
dist: xenial

language: shell

git:
  depth: 1
  quiet: true

addons:
  apt:
    packages:
      - docker-ce

stages:
  - script

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - TRAVIS_REPO_SLUG=$(echo ${TRAVIS_REPO_SLUG} | awk '{print tolower($0)}')

arch:
  - amd64
  - arm64

script:
  - docker build --tag ${TRAVIS_REPO_SLUG}:latest-${TRAVIS_ARCH} .
  - docker push ${TRAVIS_REPO_SLUG}:latest-${TRAVIS_ARCH}

jobs:
  include:
    - script:
        - docker pull ${TRAVIS_REPO_SLUG}:latest-amd64
        - docker pull ${TRAVIS_REPO_SLUG}:latest-arm64
        - docker manifest create ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH} ${TRAVIS_REPO_SLUG}:latest-amd64 ${TRAVIS_REPO_SLUG}:latest-arm64
        - docker manifest push ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}
        - docker rmi ${TRAVIS_REPO_SLUG}:latest-amd64 ${TRAVIS_REPO_SLUG}:latest-arm64