os: linux
dist: bionic

language: shell

git:
  depth: 1
  quiet: true


stages:
  - test
  - deploy

before_install:
  - sudo apt-get remove docker docker-engine docker.io containerd runc || return 0
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sed -i 's/sleep 20/sleep 0/' get-docker.sh  # skip 20s sleep
  - sudo sh get-docker.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TRAVIS_REPO_SLUG=$(echo ${TRAVIS_REPO_SLUG} | awk '{print tolower($0)}')

# begin build matrix

arch:
  - amd64
  - arm64

script:
  - if [ "$TRAVIS_ARCH" = "aarch64" ]; then export TRAVIS_ARCH=arm64; fi
  - docker build --tag ${TRAVIS_REPO_SLUG}:latest-${TRAVIS_ARCH} .
  - docker push ${TRAVIS_REPO_SLUG}:latest-${TRAVIS_ARCH}

# end build matrix, start deploy

jobs:
  include:
    - stage: deploy
      script:
        - docker pull -q ${TRAVIS_REPO_SLUG}:latest-amd64 & docker pull -q ${TRAVIS_REPO_SLUG}:latest-arm64
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - |
          for x in latest ${TRAVIS_BRANCH}; do
            docker manifest create ${TRAVIS_REPO_SLUG}:${x} ${TRAVIS_REPO_SLUG}:latest-amd64 ${TRAVIS_REPO_SLUG}:latest-arm64
            docker manifest push ${TRAVIS_REPO_SLUG}:${x}
          done
