os: linux
dist: xenial

language: shell

git:
  depth: 1
  quiet: true


stages:
  - test
  - deploy

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - TRAVIS_REPO_SLUG=$(echo ${TRAVIS_REPO_SLUG} | awk '{print tolower($0)}')

arch:
  - amd64
  - arm64

script:
  - docker build --tag ${TRAVIS_REPO_SLUG}:latest-${TRAVIS_ARCH} .
  - docker push ${TRAVIS_REPO_SLUG}:latest-${TRAVIS_ARCH}

jobs:
  include:
    - stage: deploy
      script:
        - docker pull ${TRAVIS_REPO_SLUG}:latest-amd64
        - docker pull ${TRAVIS_REPO_SLUG}:latest-arm64
        - docker manifest create ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH} ${TRAVIS_REPO_SLUG}:latest-amd64 ${TRAVIS_REPO_SLUG}:latest-arm64
        - docker manifest push ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}
        - docker rmi ${TRAVIS_REPO_SLUG}:latest-amd64 ${TRAVIS_REPO_SLUG}:latest-arm64