name: build and push to dockerhub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build and push the image
        run: |
          export REPO=($(echo ${GITHUB_REPOSITORY} | tr '/' ' '))
          export SLUG="${{ secrets.DOCKER_USERNAME }}/${REPO[1]}"
          docker buildx build \
            --tag ${SLUG}:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
          docker push ${SLUG}:latest
          if [ ! "${GITHUB_REF}" = "" ]; then
            export REFS=($(echo ${GITHUB_REF} | tr '/' ' '))
            export TAG=${REFS[2]}
            docker tag ${SLUG}:latest ${SLUG}:${TAG}
            docker push ${SLUG}:${TAG}
          fi
